services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: event-subscription-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/event-subscription-manager
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: 123456
      DATASOURCE_DRIVER: org.postgresql.Driver
volumes:
  postgres_data: