services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - "${DATASOURCE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    ports:
      - ${API_PORT}:8080
      - ${API_DEBUG_PORT}:5005
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_DRIVER: org.postgresql.Driver
volumes:
  postgres_data: