name: Release Deployment to Render via GHCR

on:
  release:
    types: [ created ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Create dependencies
        run: mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

      - name: Build and push Docker image (tagged)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Trigger Render deploy via API
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${TAG}"
          
          echo "Updating Render image to $IMAGE..."
          
          curl -X PATCH https://api.render.com/v1/services/$RENDER_SERVICE_ID \
            -H "Authorization: Bearer $RENDER_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"image\": {\"url\": \"$IMAGE\"}}"
          
          echo "Triggering deployment..."
          
          curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -H "Authorization: Bearer $RENDER_API_TOKEN"
